export const links =[
    {
        name:'Home',
        path:'/hospital'
    },{
        name:'Reservations',
        path:'/hospital/reservations'
    },
    {
        name:'Cases',
        path:'/hospital/emergency_cases'
    },
    {
        name:'Doctors',
        path:'/hospital/doctors'
    },
    {
        name:'Rooms',
        path:'/hospital/rooms'
    },
    {
        name:'Clincals',
        path:'/hospital/clincals'
    },
    {
        name:'Profile',
        path:'#'
    },
    {
        name:'Settings',
        path:'#'
    }
]