import { useAuth } from '@/Hooks/doctorAuth '
import Head from 'next/head'
import DoctorNav from '../Navbars/DoctorNav'
import styles from '../../styles/Doctor/Home.module.css'






export default function DoctorLayout({token , user , container}) {
    return (
        <div className={styles.container}>
            <Head>
            <title>  EgyHealth ~ Doctor</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <DoctorNav token={token} doctor={user} />
            </header>
            <main className={styles.main}>
                {container}
            </main>
            <footer className={styles.footer}>
                <p>Copyright © 2022 egyhealth</p>
            </footer>
        </div>
    )
}
