import { useAuth } from '@/Hooks/hospitalAuth '
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Hospital/Layout.module.css'
import HospitalNav from '../Navbars/HospitalNav'
import HospitalSidebar from '../Sidebar/HospitalSidebar'
import {  easeInOut, motion } from 'framer-motion'


export default function HospitalLayout({title , container}) {
    const {user} = useAuth({'middleware':"auth" , 'redirectIfAuthenticated': ''})
    return (
        <div className={styles.container}>
            <Head>
            <title> {title ? title + '~ EgyHealth': 'EgyHealth'} </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <HospitalNav hospital={user} />
            </header>
            <main className={styles.main}>
                <div className={styles.Sidebar}>
                    <HospitalSidebar />
                </div>
                <div className={styles.containerr}>
                    <motion.div initail={{x:-300 , y:-300 , opacity:0}} 
                    animate={{x:0 , y:0 , opacity:1}}
                    end={{x:-300 , y:-300 , opacity:0}}
                    transition={{type:'spring' , duration:0.4 , delay:0.3 , ease:easeInOut}}>
                        {container}
                    </motion.div>
                </div>
                
            </main>
            <footer className={styles.footer}>
                <p>Copyright © 2022 egyhealth</p>
            </footer>
        </div>
    )
}
