import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import UserNav from '../Navbars/UserNav'
import { useAuth } from '@/Hooks/auth '



export default function Layout({ title , container , className , token}) {
    return (
        <div className={className === 'coverContainer'? styles.coverContainer: styles.fillContainer}>
            <Head>
            <title> {String(title ? title + '~ EgyHealth': 'EgyHealth')} </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <UserNav token={token} />
            </header>
            <main className={styles.main}>
                {container}
            </main>
            <footer className={styles.footer}>
                <p>Copyright © 2022 egyhealth</p>
            </footer>
        </div>
    )
}
